# Site
title: "Fatemeh Rajabi"
bio: "M.Sc of AI, Data Scientist, Research Assistant"
description: "Graduated in Artificial Intelligence/Computer Science"
reading_time: true
words_per_minute: 200
logo: "assets/img/IMG_20250130_190718.jpg"
background: "assets/img/moonrise-background.jpg"
tiled_bg: false # Set this true if you want to tile your background image, otherwise it will be covered
locale: 
url: https://rjbi-ftmh.github.io/

# Jekyll
permalink: /:title/
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
mathjax: true
sass:
  sass_dir: _sass
  style: compressed

# Comments

# Social
# if you don't have any of social below, comment the line.
#google:
# plus: username
#analytics:
#verify:
#ad-client:
#ad-slot:
#bing-verify:
email: rjbi.ftmh@gmail.com
twitter: rjbi_ftmh
#facebook: username
github-url: rjbi-ftmh
#stackoverflow: 123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin: lfatemerajabil
#xing: username
#instagram: username
#lastfm: username
#tumblr: username
#medium: '@username'
#pinterest: username
#foursquare: username
#steam: username
#dribbble: username
#youtube: username
#youtube-channel: channel
#soundcloud: username
#weibo: username
#flickr: username
#codepen: username
#keybase: username
#xmpp: username@server.com
#hackernews: username
google scholar: https://scholar.google.com/citations?user=zxTU4UwAAAAJ&hl=en

# Plugins
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache

jekyll-mentions:
  base_url: https://github.com

# Exclude list
exclude:
  [
    README.md,
    Gemfile,
    Gemfile.lock,
    node_modules,
    gulpfile.js,
    package.json,
    _site,
    src,
    vendor,
    CNAME,
    LICENSE,
    Rakefile,
  ]
